name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ prod ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with : 
          python-version : 3.8

      - name: install dependencies
        run: make install

      - name: lint
        run: make lint

      - name: test
        run: make test

      - name: format
        run: make format
